# Generated by Django 4.1.4 on 2022-12-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=256)),
                ("final_filename", models.CharField(max_length=256, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Done", "Done"),
                            ("Error", "Error"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
