# Generated by Django 4.1.4 on 2023-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadtask",
            name="fits_header",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="uploadtask",
            name="initial_fits_header",
            field=models.JSONField(null=True),
        ),
    ]
