# Generated by Django 4.1.4 on 2023-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_uploadtask_fits_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadtask",
            name="local_destination",
            field=models.CharField(default="initial", max_length=256),
            preserve_default=False,
        ),
    ]
